#!/usr/bin/env python


import sys
import json
import codecs
from warnings import warn
from eth_utils import to_bytes, from_wei, to_wei
from web3 import Web3


def main(contract_address, destination_address, amount):
    with open('../build/MultiSig2of3.abi') as abi_file:
        abi = json.load(abi_file)

    dest = Web3.toChecksumAddress(destination_address)
        
    from my_eth_util import create_node
    w3 = create_node(2)
    chain_id = w3.net.chainId
    gas_price = w3.eth.generateGasPrice()
    if gas_price:
        print("Current gas price is: {}".format(gas_price))
    else:
        print("Error while recieving gas price. Stopping")
        sys.exit(1)
    
    contract = w3.eth.contract(address=contract_address, abi=abi)
    wei = to_wei(amount, 'ether')
    message = contract.call().generateMessageToSign(dest, wei)

    # https://github.com/ethereum/web3.py/issues/193
    print(to_bytes(message).hex())
    

if __name__ == '__main__':
    if (len(sys.argv) < 4):
        sys.exit("USAGE: ethereum_multisig_spend_unsigned_data CONTRACT_ADDRESS DESTINATION_ADDRESS AMOUNT")
    main(sys.argv[1], sys.argv[2], sys.argv[3])
