#!/usr/bin/env python

import sys  
import getpass

from web3.auto import w3
from eth_account.messages import defunct_hash_message


def main(message,file_path):

    with open(file_path) as keyfile:
        encrypted_key = keyfile.read()
        pswd = getpass.getpass('Enter keystore password:')
        private_key = w3.eth.account.decrypt(encrypted_key, pswd)
        account = w3.eth.account.privateKeyToAccount(private_key)
        
    message_hash = defunct_hash_message(text=message)
    signed_message = w3.eth.account.signHash(message_hash, private_key=private_key)
    print(signed_message)

    # Parse sig for r,s,v
    #print(sig.signature.hex())

if __name__ == '__main__':
    if (len(sys.argv) < 2):
        sys.exit("USAGE: sign_multisig_with_keystore MESSAGE KEYSTORE_PATH")
    main(sys.argv[1],sys.argv[2])
